apiVersion: v1
kind: Service
metadata:
  name: hadoop
spec:
  type: LoadBalancer
  loadBalancerIP: 34.66.52.229
  ports:
    - name: namenode-ui
      port: 50070
      targetPort: 50070
      protocol: TCP
    - name: resourcemanager-ui
      port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: hadoop
