apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  loadBalancerIP: ## change to your load balancer IP
  ports:
    - name: jenkins-port  # 为端口提供一个名称
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins