apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
spec:
  type: LoadBalancer
  loadBalancerIP: 34.133.226.219
  ports:
    - name: notebook-port  # 为端口提供一个名称
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: jupyter-notebook
