apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  type: LoadBalancer
  loadBalancerIP: 35.202.249.189
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: sonarqube