apiVersion: v1
kind: Service
metadata:
  name: spark
spec:
  type: LoadBalancer
  loadBalancerIP: 34.170.65.170
  ports:
    - name: spark-port  # 为端口提供一个名称
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spark